-- DB SCHEMA
CREATE TABLE uTable (
	--UID SERIAL PRIMARY KEY,
	NAME VARCHAR(20) PRIMARY KEY
);

CREATE TABLE links(
	URL VARCHAR(2000) NOT NULL,
	UID VARCHAR(20) REFERENCES uTable(name) NOT NULL
);